### ISSUE TITLE
Update for newer logstash versions

### ISSUE THREAD

**Issue by mjnorman** [tintoy/logstash-output-seq#1]
Hi there.  I am attempting to use this plugin on a windows host running latest version of logstash.  Would it be possible to update this to allow for later versions of logstash?

**Comment by tintoy** [comment]
Hi - sorry, it's been a while since I worked on this but sure I can't see any reason why not. Let me have a look at what's required and get back to you (I'm in AU so it's Friday morning; I may not have time to work on this until the weekend) :)

**Comment by mjnorman** [comment]
Thanks!  I gave it a try on my fork, but I am still very new to Ruby.  I had some trouble with the dependencies.  One thing I do know is that for version 6.x, they eliminated direct element references such as event['field'], so you have to use event.get('field').

**Comment by tintoy** [comment]
Hmm - I no longer have a mac, and jRuby doesn't work so well in WSL (so I can't build or run this code at the moment).

It may take me a couple of days to get a Linux VM up and running to work on this :)

**Comment by mjnorman** [comment]
I’m just using Jruby for windows and it seems to work ok.  I just can’t seem to get the dependency tree right for this.

**Comment by tintoy** [comment]
I might see if I can use https://github.com/logstash-plugins/logstash-output-example as a template (it's how I wrote this one in the first place)...

**Comment by mjnorman** [comment]
It’s really funny you mention this. I started doing this in a test repo. I basically started building from ground up. Take a look here. 

https://github.com/mjnorman/mytestplugin

**Comment by mjnorman** [comment]
Well I realized I didn’t push my latest updates but I think this is probably the way to go. The biggest change was adding the github address for Logstash to the Gemfile which was not in the original. Then of course the field accessors and using `event.to_hash` instead of `event.instance_variable_get()`

**Comment by tintoy** [comment]
Cool - I'll do a diff between their latest template and the existing plugin code to see what's different; sorry it's taking a while, just have a lot going on at the moment :)

**Comment by tintoy** [comment]
Ok - I'm hoping fac25a50ee803fe4709b19df8200471e16b2bf01 will do the trick (tests pass locally, at least, but I've never tried building against Logstash source for CI which is what the latest example plugin does).

**Comment by tintoy** [comment]
Ok, can you give [v0.2.0](https://rubygems.org/gems/logstash-output-seq/versions/0.2.0) a try?

**Comment by mjnorman** [comment]
I've had it running and outputting logs to SEQ for a couple of days.  No issues so far!  Going to close the issue.  Want to give you a big thanks for all the help with this!

**Comment by tintoy** [comment]
That's great to hear! Thanks for helping out :)
